name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        qt_ver: [5.12.6]
        qt_target: [desktop]
        # mingw用不了
        qt_arch: [win64_msvc2017_64, win32_msvc2017]
        # 从矩阵中除外的配置
        exclude: 
          - qt_ver: 5.9.8
            qt_arch: win32_msvc2017
        # 额外设置msvc_arch
        include:
          - qt_arch: win64_msvc2017_64
            msvc_arch: x64
    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v3.0.0
      with: 
        # Version of Qt to install
        version: ${{ matrix.qt_ver }}
        # Target platform for build
        target: ${{ matrix.qt_target }}
        # Architecture for Windows/Android
        arch: ${{ matrix.qt_arch }}
    - uses: actions/checkout@v3
    - name: build-msvc
      shell: cmd
      env:
        vc_arch: ${{ matrix.msvc_arch}}
      run: 
        call 
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          qmake
          nmake

