name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v3.0.0
      with: 
        version: 5.15.2
        target: desktop
        arch: win64_msvc2017_64
    - uses: actions/checkout@v3

